---
- name: "Create Backend Dir"
  become: true
  file:
    path: "/home/ubuntu/backend_dir"
    state: directory


- name: "Extract Artifact"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend_dir

- name: "Install Dependencies"
  become: true
  shell: |
    cd home/ubuntu/backend_dir
    npm i

- name: "Start pm2"
  become: true
  shell: |
    cd home/ubuntu/backend_dir/dist
    pm2 delete all
    pm2 start main.js