  ---
- name: Create backend dir
  file:
    path: "~/backend-dir"
    state: directory


- name: Extract artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-dir

- name: Install dependencies
  shell: |
    cd ~/backend-dir
    npm i

- name: Start pm2
  shell: |
    cd ~/backend-dir/dist
    pm2 delete all
    pm2 start main.js